using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Singleton.Generator
{
    /// <summary>
    /// How the instance of a singleton is first made.
    /// </summary>
    internal enum SingletonInstance
    {
        /// <summary>By the parameterless constructor of the type.</summary>
        Newable,

        /// <summary>By a creator which the attribute named.</summary>
        Creator,

        /// <summary>By loading a prefab from a <c>Resources</c> folder and instantiating it.</summary>
        ResourcesMonoBehaviour,

        /// <summary>By loading an asset from a <c>Resources</c> folder.</summary>
        ResourcesScriptableObject,

        /// <summary>By loading a prefab from an Addressables catalog and instantiating it.</summary>
        AddressableMonoBehaviour,

        /// <summary>By loading an asset from an Addressables catalog.</summary>
        AddressableScriptableObject,

        /// <summary>By finding the <c>MonoBehaviour</c> Unity made, or by making one.</summary>
        MonoBehaviour,

        /// <summary>By finding the <c>ScriptableObject</c> which is loaded, or by making one.</summary>
        ScriptableObject
    }

    /// <summary>
    /// One type which asked for a singleton, with everything the half which is generated for it is written from.
    /// </summary>
    internal sealed class SingletonTarget
    {
        /// <summary>
        /// Makes a target of a type which asked for a singleton.
        /// </summary>
        /// <param name="type">The type which asked for the singleton.</param>
        /// <param name="instance">How the instance is first made.</param>
        public SingletonTarget(INamedTypeSymbol type, SingletonInstance instance)
        {
            Type = type;
            Instance = instance;
        }

        /// <summary>The type which asked for the singleton.</summary>
        public INamedTypeSymbol Type { get; }

        /// <summary>How the instance is first made.</summary>
        public SingletonInstance Instance { get; }

        /// <summary>Whether the object is to be kept across the loads of a scene.</summary>
        public bool Persistent { get; set; }

        /// <summary>Whether the object is to be taken out of the hierarchy, the Inspector and what a save writes.</summary>
        public bool Invisible { get; set; }

        /// <summary>
        /// Whether a type which this one derives from asked for a singleton of its own, so that what is written here
        /// hides what is written there rather than standing beside it.
        /// </summary>
        public bool Hides { get; set; }

        /// <summary>The path or the address which an asset is loaded by.</summary>
        public string? AssetPath { get; set; }

        /// <summary>The creator which makes the instance.</summary>
        public INamedTypeSymbol? Creator { get; set; }

        /// <summary>The constructor of the creator which the arguments are fitted to.</summary>
        public IMethodSymbol? CreatorConstructor { get; set; }

        /// <summary>The arguments which the attribute named the creator with, one to each parameter of the constructor.</summary>
        public List<TypedConstant> CreatorConstructorArguments { get; } = new();
    }

    /// <summary>
    /// Writes the half of a singleton which holds the field and the property.
    /// </summary>
    /// <remarks>
    /// Everything written here is named in full, so that the file stands on its own: it is compiled beside
    /// <c>using</c> directives which were written for another file, and a name it takes from them would be a name it
    /// takes by accident.
    /// </remarks>
    internal static class SingletonEmitter
    {
        /// <summary>What is written at the top of the file.</summary>
        private const string HEADER =
            "// <auto-generated>\n" +
            "//     This file was generated by the Singleton source generator.\n" +
            "//     It is written again on every compilation, so changes to it are lost.\n" +
            "// </auto-generated>\n" +
            "#nullable enable\n";

        /// <summary>
        /// Write the generated half of a singleton.
        /// </summary>
        /// <param name="target">The singleton.</param>
        /// <param name="arguments">What the arguments of a creator are written by.</param>
        /// <returns>The file.</returns>
        public static string Emit(SingletonTarget target, ArgumentRenderer arguments)
        {
            var builder = new StringBuilder(HEADER);
            var type = target.Type;
            var indent = string.Empty;

            builder.AppendLine();

            var wrapped = !type.ContainingNamespace.IsGlobalNamespace;
            if (wrapped)
            {
                builder.Append("namespace ").AppendLine(type.ContainingNamespace.ToDisplayString());
                builder.AppendLine("{");
                indent = "    ";
            }

            // Every type a singleton was declared inside of is declared again here, because the generated half is a
            // second declaration of the singleton and not a member inside the first one.
            var containers = Containers(type);
            foreach (var container in containers)
            {
                if (SymbolEqualityComparer.Default.Equals(container, type)) continue;

                builder.Append(indent).AppendLine(Declaration(container));
                builder.Append(indent).AppendLine("{");
                indent += "    ";
            }

            builder.Append(indent).AppendLine(Declaration(type));

            // A singleton which the compiler reads as a static interface is one which can be read through a type
            // argument alone, which is what the interface is for. It is only written where the language which compiles
            // this file has static interface members, which is what the runtime half is guarded by as well.
            builder.Append(indent).AppendLine("#if CSHARP_11_OR_NEWER");
            builder.Append(indent).Append("    : global::Singleton.Runtime.ISingleton<").Append(type.Name).AppendLine(">");
            builder.Append(indent).AppendLine("#endif");

            builder.Append(indent).AppendLine("{");
            indent += "    ";

            var qualified = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            builder.Append(indent).Append("private static ").Append(qualified).AppendLine("? s_Instance;");
            builder.AppendLine();
            builder.Append(indent).Append("public static ").Append(qualified).AppendLine(" Instance");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            builder.Append(indent).AppendLine("    get");
            builder.Append(indent).AppendLine("    {");

            WriteBody(builder, indent + "        ", target, arguments, qualified);

            builder.Append(indent).AppendLine("    }");
            builder.Append(indent).AppendLine("}");

            // What a caller which must not bring a singleton into being reads: the property makes the instance where
            // there is none, and a message which may run before the one which would have made it is a message which
            // cannot ask the property whether there is one at all.
            builder.AppendLine();
            builder.Append(indent).AppendLine("/// <summary>The instance of the singleton where there is one, which is answered without making one.</summary>");
            builder.Append(indent).AppendLine("/// <param name=\"instance\">The instance, where there is one.</param>");
            builder.Append(indent).AppendLine("/// <returns>Whether there is one.</returns>");
            builder.Append(indent).Append("public static bool TryGetInstance(out ").Append(qualified).AppendLine(" instance)");
            builder.Append(indent).AppendLine("{");
            builder.Append(indent).AppendLine("    instance = s_Instance!;");
            builder.Append(indent).AppendLine("    return instance != null;");
            builder.Append(indent).AppendLine("}");

            // The brace of a declaration is written one step further out than what it holds, so every declaration is
            // closed by stepping out and then writing.
            indent = Outdent(indent);
            builder.Append(indent).AppendLine("}");

            for (var index = containers.Count - 2; index >= 0; index--)
            {
                indent = Outdent(indent);
                builder.Append(indent).AppendLine("}");
            }

            if (wrapped)
            {
                indent = Outdent(indent);
                builder.Append(indent).AppendLine("}");
            }

            return builder.ToString();
        }

        /// <summary>
        /// Step an indentation out by one declaration.
        /// </summary>
        /// <param name="indent">The indentation.</param>
        /// <returns>The indentation of the declaration which holds the type.</returns>
        private static string Outdent(string indent) => indent.Substring(0, indent.Length - 4);

        /// <summary>
        /// Write the body of the getter, which makes the instance where there is none and returns it.
        /// </summary>
        /// <param name="builder">The file.</param>
        /// <param name="indent">What the body is indented with.</param>
        /// <param name="target">The singleton.</param>
        /// <param name="arguments">What the arguments of a creator are written by.</param>
        /// <param name="qualified">The name of the type, written in full.</param>
        private static void WriteBody(StringBuilder builder, string indent, SingletonTarget target,
                                      ArgumentRenderer arguments, string qualified)
        {
            switch (target.Instance)
            {
                case SingletonInstance.Newable:
                    builder.Append(indent).AppendLine("if (s_Instance == null)");
                    builder.Append(indent).AppendLine("{");
                    builder.Append(indent).Append("    s_Instance = new ").Append(qualified).AppendLine("();");
                    builder.Append(indent).AppendLine("}");
                    break;

                case SingletonInstance.Creator:
                    var creator = target.Creator!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    builder.Append(indent).AppendLine("if (s_Instance == null)");
                    builder.Append(indent).AppendLine("{");
                    builder.Append(indent).Append("    s_Instance = new ").Append(creator).Append('(');
                    WriteArguments(builder, target, arguments);
                    builder.AppendLine(").Create();");
                    builder.Append(indent).AppendLine("}");
                    break;

                case SingletonInstance.MonoBehaviour:
                    builder.Append(indent).AppendLine("if (s_Instance == null)");
                    builder.Append(indent).AppendLine("{");
                    WriteFind(builder, indent + "    ", qualified);
                    builder.Append(indent).AppendLine("    if (s_Instance == null)");
                    builder.Append(indent).AppendLine("    {");
                    builder.Append(indent).Append("        var go = new global::UnityEngine.GameObject(nameof(").Append(target.Type.Name).AppendLine("));");
                    builder.Append(indent).AppendLine("        go.SetActive(false);");
                    builder.Append(indent).Append("        s_Instance = go.AddComponent<").Append(qualified).AppendLine(">();");
                    builder.Append(indent).AppendLine("        go.SetActive(true);");
                    builder.Append(indent).AppendLine("    }");
                    builder.Append(indent).AppendLine("}");
                    break;

                case SingletonInstance.ScriptableObject:
                    builder.Append(indent).AppendLine("if (s_Instance == null)");
                    builder.Append(indent).AppendLine("{");
                    WriteFind(builder, indent + "    ", qualified);
                    builder.Append(indent).Append("    if (s_Instance == null) s_Instance = global::UnityEngine.ScriptableObject.CreateInstance<")
                           .Append(qualified).AppendLine(">();");
                    builder.Append(indent).AppendLine("}");
                    break;

                case SingletonInstance.ResourcesMonoBehaviour:
                    builder.Append(indent).AppendLine("if (s_Instance == null)");
                    builder.Append(indent).AppendLine("{");
                    WriteFind(builder, indent + "    ", qualified);
                    builder.Append(indent).AppendLine("    if (s_Instance == null)");
                    builder.Append(indent).AppendLine("    {");
                    WriteAssetPath(builder, indent + "        ", target.AssetPath!);
                    builder.Append(indent).Append("        var prefab = global::UnityEngine.Resources.Load<global::UnityEngine.GameObject>(assetPath);").AppendLine();
                    builder.Append(indent).AppendLine("        if (prefab == null) throw new global::System.ArgumentException($\"Failed to load singleton resource at path: {assetPath}\");");
                    builder.Append(indent).AppendLine("        var go = global::UnityEngine.Object.Instantiate(prefab);");
                    builder.Append(indent).Append("        s_Instance = go.GetComponent<").Append(qualified).AppendLine(">();");
                    builder.Append(indent).AppendLine("    }");
                    builder.Append(indent).AppendLine("}");
                    break;

                case SingletonInstance.ResourcesScriptableObject:
                    builder.Append(indent).AppendLine("if (s_Instance == null)");
                    builder.Append(indent).AppendLine("{");
                    WriteAssetPath(builder, indent + "    ", target.AssetPath!);
                    builder.Append(indent).Append("    s_Instance = global::UnityEngine.Resources.Load<").Append(qualified).AppendLine(">(assetPath);");
                    builder.Append(indent).AppendLine("    if (s_Instance == null) throw new global::System.ArgumentException($\"Failed to load singleton resource at path: {assetPath}\");");
                    builder.Append(indent).AppendLine("}");
                    break;

                case SingletonInstance.AddressableMonoBehaviour:
                    builder.Append(indent).AppendLine("if (s_Instance == null)");
                    builder.Append(indent).AppendLine("{");
                    WriteFind(builder, indent + "    ", qualified);
                    builder.Append(indent).AppendLine("    if (s_Instance == null)");
                    builder.Append(indent).AppendLine("    {");
                    WriteAssetPath(builder, indent + "        ", target.AssetPath!);
                    builder.Append(indent).AppendLine("        var op = global::UnityEngine.AddressableAssets.Addressables.InstantiateAsync(assetPath);");
                    builder.Append(indent).AppendLine("        op.WaitForCompletion();");
                    builder.Append(indent).AppendLine("        if (op.Status != global::UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationStatus.Succeeded) throw new global::System.ArgumentException($\"Failed to load singleton resource at path: {assetPath}\");");
                    builder.Append(indent).Append("        s_Instance = op.Result.GetComponent<").Append(qualified).AppendLine(">();");
                    builder.Append(indent).AppendLine("    }");
                    builder.Append(indent).AppendLine("}");
                    break;

                case SingletonInstance.AddressableScriptableObject:
                    builder.Append(indent).AppendLine("if (s_Instance == null)");
                    builder.Append(indent).AppendLine("{");
                    WriteAssetPath(builder, indent + "    ", target.AssetPath!);
                    builder.Append(indent).Append("    var op = global::UnityEngine.AddressableAssets.Addressables.LoadAssetAsync<").Append(qualified).AppendLine(">(assetPath);");
                    builder.Append(indent).AppendLine("    op.WaitForCompletion();");
                    builder.Append(indent).AppendLine("    if (op.Status != global::UnityEngine.ResourceManagement.AsyncOperations.AsyncOperationStatus.Succeeded) throw new global::System.ArgumentException($\"Failed to load singleton resource at path: {assetPath}\");");
                    builder.Append(indent).AppendLine("    s_Instance = op.Result;");
                    builder.Append(indent).AppendLine("}");
                    break;
            }

            builder.Append(indent).AppendLine("return s_Instance!;");
        }

        /// <summary>
        /// Write the arguments which the constructor of a creator is called with.
        /// </summary>
        /// <param name="builder">The file.</param>
        /// <param name="target">The singleton.</param>
        /// <param name="arguments">What an argument is written by.</param>
        private static void WriteArguments(StringBuilder builder, SingletonTarget target, ArgumentRenderer arguments)
        {
            var parameters = target.CreatorConstructor!.Parameters;
            for (var index = 0; index < parameters.Length; index++)
            {
                if (index > 0) builder.Append(", ");
                builder.Append(arguments.Render(target.CreatorConstructorArguments[index]));
            }
        }

        /// <summary>
        /// Write the search for the instance which Unity made.
        /// </summary>
        /// <remarks>
        /// Unity 2023.1 gave the searches which name what they leave out, and the searches which came before them are
        /// the ones which are written where the compiler is an older one. What each of them leaves out is the objects
        /// which are not active, which is what the older search did without being told.
        /// </remarks>
        /// <param name="builder">The file.</param>
        /// <param name="indent">What the search is indented with.</param>
        /// <param name="qualified">The name of the type, written in full.</param>
        private static void WriteFind(StringBuilder builder, string indent, string qualified)
        {
            builder.Append(indent).AppendLine("#if UNITY_2023_1_OR_NEWER");
            builder.Append(indent).Append("s_Instance = global::UnityEngine.Object.FindAnyObjectByType<").Append(qualified)
                   .AppendLine(">(global::UnityEngine.FindObjectsInactive.Exclude);");
            builder.Append(indent).AppendLine("#else");
            builder.Append(indent).Append("s_Instance = global::UnityEngine.Object.FindObjectOfType<").Append(qualified)
                   .AppendLine(">();");
            builder.Append(indent).AppendLine("#endif");
        }

        /// <summary>
        /// Write the asset path as a constant of the getter.
        /// </summary>
        /// <param name="builder">The file.</param>
        /// <param name="indent">What the constant is indented with.</param>
        /// <param name="path">The path or the address.</param>
        private static void WriteAssetPath(StringBuilder builder, string indent, string path)
        {
            builder.Append(indent).Append("const string assetPath = ")
                   .Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(path, quote: true))
                   .AppendLine(";");
        }

        /// <summary>
        /// Read the declarations which hold a type, from the outermost one to the declaration of the type itself.
        /// </summary>
        /// <param name="type">The type.</param>
        /// <returns>The declarations.</returns>
        private static List<INamedTypeSymbol> Containers(INamedTypeSymbol type)
        {
            var containers = new List<INamedTypeSymbol>();
            for (var current = type; current != null; current = current.ContainingType) containers.Add(current);
            containers.Reverse();
            return containers;
        }

        /// <summary>
        /// Write the declaration of a type, without what a partial declaration may leave out.
        /// </summary>
        /// <param name="type">The type.</param>
        /// <returns>The declaration.</returns>
        private static string Declaration(INamedTypeSymbol type)
        {
            var keyword = type.TypeKind switch
            {
                TypeKind.Struct => "struct",
                TypeKind.Interface => "interface",
                _ => type.IsRecord ? "record" : "class"
            };

            return $"{Accessibility(type)} partial {keyword} {type.Name}";
        }

        /// <summary>
        /// Write the accessibility which a type declared, and which a partial declaration of it has to agree with.
        /// </summary>
        /// <param name="type">The type.</param>
        /// <returns>The accessibility.</returns>
        private static string Accessibility(INamedTypeSymbol type) => type.DeclaredAccessibility switch
        {
            Microsoft.CodeAnalysis.Accessibility.Public => "public",
            Microsoft.CodeAnalysis.Accessibility.Private => "private",
            Microsoft.CodeAnalysis.Accessibility.Protected => "protected",
            Microsoft.CodeAnalysis.Accessibility.ProtectedOrInternal => "protected internal",
            Microsoft.CodeAnalysis.Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };
    }
}